title: SMaSH-IT Training
name: SMaSH-IT Training
homepage: /index.html
description: Training and professional development for computing and emerging technologies in Cardiff, Bridgend and South Wales, working with primary, secondary and above.
url: https://smash-it.co.uk
author:
  name: Scott Morgan
  twitter: scott3142
  url: http://scott3142.com

image: /images/author.jpg
lang: en

social:
  name: SMaSH-IT training
  links:
    https://github.com/SMaSH-IT-Training/

include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
